[build]
command = ""
publish = "."

[build.environment]
NODE_VERSION = "18"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/feedback"
  to = "/feedback.html"
  status = 200

[[redirects]]
  from = "/feedback/"
  to = "/feedback.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/"
  to = "/admin/index.html"
  status = 200
